### ISSUE TITLE
Load JSON body data from file

### ISSUE THREAD

**Issue by samdods** [KaneCheshire/Peasy#9]
It would be nice if you could load JSON from a file to respond with, like so:

```
extension Response {
    public init(status: Status, headers: [Header] = [], bodyFromJSONFile: String) {
        // load body data as JSON from given file
    }
}
```

**Comment by KaneCheshire** [comment]
Wouldn't be impossible for sure, and not too much extra hassle to add a new init either. Would there be a way to automatically detect the right bundle from within the Response's int? Would be nasty to expect people to also pass in a bundle so would want to avoid that if possible

**Comment by KaneCheshire** [comment]
Ah I know, if I create an init that takes a URL to load you can just pass in the URL to a file, so Peasy doesn't need to care about the bundle.
